```{r}
# dataset <- redivis::organization("datapages")$dataset("palmerpenguins")
# penguins <- dataset$table("penguins")$to_tibble()
# ojs_define(data = penguins)
```

```{r}
quarto <- yaml::read_yaml("_quarto.yml")

# load data from redivis table if specified in yaml
if ("redivis" %in% names(quarto) &&
  all(c("table") %in% names(quarto$redivis)) && # need table
  any(c("user", "organization") %in% names(quarto$redivis)) && # need user or organization
  any(c("dataset", "project") %in% names(quarto$redivis))) { # need dataset or project
  # get the account (user or organization)
  if (!is.null(quarto$redivis$organization)) {
    account <- redivis::organization(quarto$redivis$organization)
  } else {
    account <- redivis::user(quarto$redivis$user)
  }
  if (!is.null(quarto$redivis$dataset)) {
    # use dataset if provided
    dataset <- account$dataset(quarto$redivis$dataset)
  } else {
    # otherwise use project
    dataset <- account$project(quarto$redivis$project)
  }

  # get table data
  table <- dataset$table(quarto$redivis$table)
  data <- table$to_tibble()

  # get variable metadata
  vars <- map(table$list_variables(), \(v) v$get()$properties)

  # pass to OJS
  ojs_define(data = data)
  ojs_define(vars = vars)
} else {
  ojs_define(data = NULL)
  ojs_define(vars = NULL)
}
```




```{ojs}
Plot = import("https://esm.sh/@observablehq/plot@0.6.13")
d = transpose(data)


disc_types = ['string', 'boolean']
disc_vars = vars.filter(d => disc_types.includes(d.type)).map(d => [d.label ? d.label : d.name, d.name])
disc_opts = new Map([['', null]].concat(disc_vars))

cont_types = ['integer', 'float', 'date', 'datetime', 'time']
cont_vars = vars.filter(d => cont_types.includes(d.type)).map(d => [d.label ? d.label : d.name, d.name])
cont_opts = new Map(cont_vars)
```
